QT.Attica.VERSION = 5.27.0
QT.Attica.MAJOR_VERSION = 5
QT.Attica.MINOR_VERSION = 27
QT.Attica.PATCH_VERSION = 0
QT.Attica.name = KF5Attica
QT.Attica.defines = 
QT.Attica.includes = /kate.appdir/usr/include/KF5/Attica
QT.Attica.private_includes =
QT.Attica.libs = /kate.appdir/usr/lib64
QT.Attica.depends = core
