QT.KTextEditor.VERSION = 5.27.0
QT.KTextEditor.MAJOR_VERSION = 5
QT.KTextEditor.MINOR_VERSION = 27
QT.KTextEditor.PATCH_VERSION = 0
QT.KTextEditor.name = KF5TextEditor
QT.KTextEditor.defines = 
QT.KTextEditor.includes = /kate.appdir/usr/include/KF5/KTextEditor
QT.KTextEditor.private_includes =
QT.KTextEditor.libs = /kate.appdir/usr/lib64
QT.KTextEditor.depends = KParts
