QT.KJobWidgets.VERSION = 5.27.0
QT.KJobWidgets.MAJOR_VERSION = 5
QT.KJobWidgets.MINOR_VERSION = 27
QT.KJobWidgets.PATCH_VERSION = 0
QT.KJobWidgets.name = KF5JobWidgets
QT.KJobWidgets.defines = 
QT.KJobWidgets.includes = /kate.appdir/usr/include/KF5/KJobWidgets
QT.KJobWidgets.private_includes =
QT.KJobWidgets.libs = /kate.appdir/usr/lib64
QT.KJobWidgets.depends = widgets KCoreAddons
