QT.KNewStuff.VERSION = 5.27.0
QT.KNewStuff.MAJOR_VERSION = 5
QT.KNewStuff.MINOR_VERSION = 27
QT.KNewStuff.PATCH_VERSION = 0
QT.KNewStuff.name = KF5NewStuff
QT.KNewStuff.defines = 
QT.KNewStuff.includes = /kate.appdir/usr/include/KF5/KNewStuff
QT.KNewStuff.private_includes =
QT.KNewStuff.libs = /kate.appdir/usr/lib64
QT.KNewStuff.depends = widgets Attica KXmlGui
