QT.KItemModels.VERSION = 5.27.0
QT.KItemModels.MAJOR_VERSION = 5
QT.KItemModels.MINOR_VERSION = 27
QT.KItemModels.PATCH_VERSION = 0
QT.KItemModels.name = KF5ItemModels
QT.KItemModels.defines = 
QT.KItemModels.includes = /kate.appdir/usr/include/KF5/KItemModels
QT.KItemModels.private_includes =
QT.KItemModels.libs = /kate.appdir/usr/lib64
QT.KItemModels.depends = core
