QT.KIOCore.VERSION = 5.27.0
QT.KIOCore.MAJOR_VERSION = 5
QT.KIOCore.MINOR_VERSION = 27
QT.KIOCore.PATCH_VERSION = 0
QT.KIOCore.name = KF5KIOCore
QT.KIOCore.defines = 
QT.KIOCore.includes = /kate.appdir/usr/include/KF5/KIOCore
QT.KIOCore.private_includes =
QT.KIOCore.libs = /kate.appdir/usr/lib64
QT.KIOCore.depends = KCoreAddons KService
