QT.KCodecs.VERSION = 5.27.0
QT.KCodecs.MAJOR_VERSION = 5
QT.KCodecs.MINOR_VERSION = 27
QT.KCodecs.PATCH_VERSION = 0
QT.KCodecs.name = KF5Codecs
QT.KCodecs.defines = 
QT.KCodecs.includes = /kate.appdir/usr/include/KF5/KCodecs
QT.KCodecs.private_includes =
QT.KCodecs.libs = /kate.appdir/usr/lib64
QT.KCodecs.depends = core
