QT.KConfigCore.VERSION = 5.27.0
QT.KConfigCore.MAJOR_VERSION = 5
QT.KConfigCore.MINOR_VERSION = 27
QT.KConfigCore.PATCH_VERSION = 0
QT.KConfigCore.name = KF5ConfigCore
QT.KConfigCore.defines = 
QT.KConfigCore.includes = /kate.appdir/usr/include/KF5/KConfigCore
QT.KConfigCore.private_includes =
QT.KConfigCore.libs = /kate.appdir/usr/lib64
QT.KConfigCore.depends = core
