QT.KConfigWidgets.VERSION = 5.27.0
QT.KConfigWidgets.MAJOR_VERSION = 5
QT.KConfigWidgets.MINOR_VERSION = 27
QT.KConfigWidgets.PATCH_VERSION = 0
QT.KConfigWidgets.name = KF5ConfigWidgets
QT.KConfigWidgets.defines = 
QT.KConfigWidgets.includes = /kate.appdir/usr/include/KF5/KConfigWidgets
QT.KConfigWidgets.private_includes =
QT.KConfigWidgets.libs = /kate.appdir/usr/lib64
QT.KConfigWidgets.depends = KCodecs KWidgetsAddons KConfigGui KAuth
