QT.KCMUtils.VERSION = 5.27.0
QT.KCMUtils.MAJOR_VERSION = 5
QT.KCMUtils.MINOR_VERSION = 27
QT.KCMUtils.PATCH_VERSION = 0
QT.KCMUtils.name = KF5KCMUtils
QT.KCMUtils.defines = 
QT.KCMUtils.includes = /kate.appdir/usr/include/KF5/KCMUtils
QT.KCMUtils.private_includes =
QT.KCMUtils.libs = /kate.appdir/usr/lib64
QT.KCMUtils.depends = widgets KConfigWidgets KService
