QT.KNTLM.VERSION = 5.27.0
QT.KNTLM.MAJOR_VERSION = 5
QT.KNTLM.MINOR_VERSION = 27
QT.KNTLM.PATCH_VERSION = 0
QT.KNTLM.name = KF5KIONTLM
QT.KNTLM.defines = 
QT.KNTLM.includes = /kate.appdir/usr/include/KF5/KNTLM
QT.KNTLM.private_includes =
QT.KNTLM.libs = /kate.appdir/usr/lib64
QT.KNTLM.depends = KCoreAddons
