QT.KTextWidgets.VERSION = 5.27.0
QT.KTextWidgets.MAJOR_VERSION = 5
QT.KTextWidgets.MINOR_VERSION = 27
QT.KTextWidgets.PATCH_VERSION = 0
QT.KTextWidgets.name = KF5TextWidgets
QT.KTextWidgets.defines = 
QT.KTextWidgets.includes = /kate.appdir/usr/include/KF5/KTextWidgets
QT.KTextWidgets.private_includes =
QT.KTextWidgets.libs = /kate.appdir/usr/lib64
QT.KTextWidgets.depends = widgets SonnetUi KI18n
