QT.KService.VERSION = 5.27.0
QT.KService.MAJOR_VERSION = 5
QT.KService.MINOR_VERSION = 27
QT.KService.PATCH_VERSION = 0
QT.KService.name = KF5Service
QT.KService.defines = 
QT.KService.includes = /kate.appdir/usr/include/KF5/KService
QT.KService.private_includes =
QT.KService.libs = /kate.appdir/usr/lib64
QT.KService.depends = KConfigCore
