QT.KCoreAddons.VERSION = 5.27.0
QT.KCoreAddons.MAJOR_VERSION = 5
QT.KCoreAddons.MINOR_VERSION = 27
QT.KCoreAddons.PATCH_VERSION = 0
QT.KCoreAddons.name = KF5CoreAddons
QT.KCoreAddons.defines = 
QT.KCoreAddons.includes = /kate.appdir/usr/include/KF5/KCoreAddons
QT.KCoreAddons.private_includes =
QT.KCoreAddons.libs = /kate.appdir/usr/lib64
QT.KCoreAddons.depends = core
