QT.KNotifications.VERSION = 5.27.0
QT.KNotifications.MAJOR_VERSION = 5
QT.KNotifications.MINOR_VERSION = 27
QT.KNotifications.PATCH_VERSION = 0
QT.KNotifications.name = KF5Notifications
QT.KNotifications.defines = 
QT.KNotifications.includes = /kate.appdir/usr/include/KF5/KNotifications
QT.KNotifications.private_includes =
QT.KNotifications.libs = /kate.appdir/usr/lib64
QT.KNotifications.depends = widgets
