QT.KDeclarative.VERSION = 5.27.0
QT.KDeclarative.MAJOR_VERSION = 5
QT.KDeclarative.MINOR_VERSION = 27
QT.KDeclarative.PATCH_VERSION = 0
QT.KDeclarative.name = KF5Declarative
QT.KDeclarative.defines = 
QT.KDeclarative.includes = /kate.appdir/usr/include/KF5/KDeclarative
QT.KDeclarative.private_includes =
QT.KDeclarative.libs = /kate.appdir/usr/lib64
QT.KDeclarative.depends = qml
