QT.KDBusAddons.VERSION = 5.27.0
QT.KDBusAddons.MAJOR_VERSION = 5
QT.KDBusAddons.MINOR_VERSION = 27
QT.KDBusAddons.PATCH_VERSION = 0
QT.KDBusAddons.name = KF5DBusAddons
QT.KDBusAddons.defines = 
QT.KDBusAddons.includes = /kate.appdir/usr/include/KF5/KDBusAddons
QT.KDBusAddons.private_includes =
QT.KDBusAddons.libs = /kate.appdir/usr/lib64
QT.KDBusAddons.depends = dbus
