QT.KWidgetsAddons.VERSION = 5.27.0
QT.KWidgetsAddons.MAJOR_VERSION = 5
QT.KWidgetsAddons.MINOR_VERSION = 27
QT.KWidgetsAddons.PATCH_VERSION = 0
QT.KWidgetsAddons.name = KF5WidgetsAddons
QT.KWidgetsAddons.defines = 
QT.KWidgetsAddons.includes = /kate.appdir/usr/include/KF5/KWidgetsAddons
QT.KWidgetsAddons.private_includes =
QT.KWidgetsAddons.libs = /kate.appdir/usr/lib64
QT.KWidgetsAddons.depends = widgets
