QT.KArchive.VERSION = 5.27.0
QT.KArchive.MAJOR_VERSION = 5
QT.KArchive.MINOR_VERSION = 27
QT.KArchive.PATCH_VERSION = 0
QT.KArchive.name = KF5Archive
QT.KArchive.defines = 
QT.KArchive.includes = /kate.appdir/usr/include/KF5/KArchive
QT.KArchive.private_includes =
QT.KArchive.libs = /kate.appdir/usr/lib64
QT.KArchive.depends = core
