QT.KGlobalAccel.VERSION = 5.27.0
QT.KGlobalAccel.MAJOR_VERSION = 5
QT.KGlobalAccel.MINOR_VERSION = 27
QT.KGlobalAccel.PATCH_VERSION = 0
QT.KGlobalAccel.name = KF5GlobalAccel
QT.KGlobalAccel.defines = 
QT.KGlobalAccel.includes = /kate.appdir/usr/include/KF5/KGlobalAccel
QT.KGlobalAccel.private_includes =
QT.KGlobalAccel.libs = /kate.appdir/usr/lib64
QT.KGlobalAccel.depends = dbus widgets
