QT.KCrash.VERSION = 5.27.0
QT.KCrash.MAJOR_VERSION = 5
QT.KCrash.MINOR_VERSION = 27
QT.KCrash.PATCH_VERSION = 0
QT.KCrash.name = KF5Crash
QT.KCrash.defines = 
QT.KCrash.includes = /kate.appdir/usr/include/KF5/KCrash
QT.KCrash.private_includes =
QT.KCrash.libs = /kate.appdir/usr/lib64
QT.KCrash.depends = core
