QT.KIconThemes.VERSION = 5.27.0
QT.KIconThemes.MAJOR_VERSION = 5
QT.KIconThemes.MINOR_VERSION = 27
QT.KIconThemes.PATCH_VERSION = 0
QT.KIconThemes.name = KF5IconThemes
QT.KIconThemes.defines = 
QT.KIconThemes.includes = /kate.appdir/usr/include/KF5/KIconThemes
QT.KIconThemes.private_includes =
QT.KIconThemes.libs = /kate.appdir/usr/lib64
QT.KIconThemes.depends = widgets
