QT.KParts.VERSION = 5.27.0
QT.KParts.MAJOR_VERSION = 5
QT.KParts.MINOR_VERSION = 27
QT.KParts.PATCH_VERSION = 0
QT.KParts.name = KF5Parts
QT.KParts.defines = 
QT.KParts.includes = /kate.appdir/usr/include/KF5/KParts
QT.KParts.private_includes =
QT.KParts.libs = /kate.appdir/usr/lib64
QT.KParts.depends = KIOWidgets KXmlGui KTextWidgets
