QT.KBookmarks.VERSION = 5.27.0
QT.KBookmarks.MAJOR_VERSION = 5
QT.KBookmarks.MINOR_VERSION = 27
QT.KBookmarks.PATCH_VERSION = 0
QT.KBookmarks.name = KF5Bookmarks
QT.KBookmarks.defines = 
QT.KBookmarks.includes = /kate.appdir/usr/include/KF5/KBookmarks
QT.KBookmarks.private_includes =
QT.KBookmarks.libs = /kate.appdir/usr/lib64
QT.KBookmarks.depends = widgets xml
