QT.KXmlGui.VERSION = 5.27.0
QT.KXmlGui.MAJOR_VERSION = 5
QT.KXmlGui.MINOR_VERSION = 27
QT.KXmlGui.PATCH_VERSION = 0
QT.KXmlGui.name = KF5XmlGui
QT.KXmlGui.defines = 
QT.KXmlGui.includes = /kate.appdir/usr/include/KF5/KXmlGui
QT.KXmlGui.private_includes =
QT.KXmlGui.libs = /kate.appdir/usr/lib64
QT.KXmlGui.depends = dbus xml widgets KConfigCore KConfigWidgets
