QT.KPty.VERSION = 5.27.0
QT.KPty.MAJOR_VERSION = 5
QT.KPty.MINOR_VERSION = 27
QT.KPty.PATCH_VERSION = 0
QT.KPty.name = KF5Pty
QT.KPty.defines = 
QT.KPty.includes = /kate.appdir/usr/include/KF5/KPty
QT.KPty.private_includes =
QT.KPty.libs = /kate.appdir/usr/lib64
QT.KPty.depends = core KCoreAddons
