QT.KNotifyConfig.VERSION = 5.27.0
QT.KNotifyConfig.MAJOR_VERSION = 5
QT.KNotifyConfig.MINOR_VERSION = 27
QT.KNotifyConfig.PATCH_VERSION = 0
QT.KNotifyConfig.name = KF5NotifyConfig
QT.KNotifyConfig.defines = 
QT.KNotifyConfig.includes = /kate.appdir/usr/include/KF5/KNotifyConfig
QT.KNotifyConfig.private_includes =
QT.KNotifyConfig.libs = /kate.appdir/usr/lib64
QT.KNotifyConfig.depends = widgets
