QT.KIOGui.VERSION = 5.27.0
QT.KIOGui.MAJOR_VERSION = 5
QT.KIOGui.MINOR_VERSION = 27
QT.KIOGui.PATCH_VERSION = 0
QT.KIOGui.name = KF5KIOGui
QT.KIOGui.defines = 
QT.KIOGui.includes = /kate.appdir/usr/include/KF5/KIOGui
QT.KIOGui.private_includes =
QT.KIOGui.libs = /kate.appdir/usr/lib64
QT.KIOGui.depends = KIOCore
