QT.KWindowSystem.VERSION = 5.27.0
QT.KWindowSystem.MAJOR_VERSION = 5
QT.KWindowSystem.MINOR_VERSION = 27
QT.KWindowSystem.PATCH_VERSION = 0
QT.KWindowSystem.name = KF5WindowSystem
QT.KWindowSystem.defines = 
QT.KWindowSystem.includes = /kate.appdir/usr/include/KF5/KWindowSystem
QT.KWindowSystem.private_includes =
QT.KWindowSystem.libs = /kate.appdir/usr/lib64
QT.KWindowSystem.depends = gui
