QT.QuickAddons.VERSION = 5.27.0
QT.QuickAddons.MAJOR_VERSION = 5
QT.QuickAddons.MINOR_VERSION = 27
QT.QuickAddons.PATCH_VERSION = 0
QT.QuickAddons.name = KF5QuickAddons
QT.QuickAddons.defines = 
QT.QuickAddons.includes = /kate.appdir/usr/include/KF5/QuickAddons
QT.QuickAddons.private_includes =
QT.QuickAddons.libs = /kate.appdir/usr/lib64
QT.QuickAddons.depends = qml
