QT.SonnetUi.VERSION = 5.27.0
QT.SonnetUi.MAJOR_VERSION = 5
QT.SonnetUi.MINOR_VERSION = 27
QT.SonnetUi.PATCH_VERSION = 0
QT.SonnetUi.name = KF5SonnetUi
QT.SonnetUi.defines = 
QT.SonnetUi.includes = /kate.appdir/usr/include/KF5/SonnetUi
QT.SonnetUi.private_includes =
QT.SonnetUi.libs = /kate.appdir/usr/lib64
QT.SonnetUi.depends = widgets
