QT.Solid.VERSION = 5.27.0
QT.Solid.MAJOR_VERSION = 5
QT.Solid.MINOR_VERSION = 27
QT.Solid.PATCH_VERSION = 0
QT.Solid.name = KF5Solid
QT.Solid.defines = 
QT.Solid.includes = /kate.appdir/usr/include/KF5/Solid
QT.Solid.private_includes =
QT.Solid.libs = /kate.appdir/usr/lib64
QT.Solid.depends = core
